-- MIGRACIÓN: Maestro de Centros de Costo
-- Fecha: 2026-04-25
-- Motivo: hasta ahora centro_costo era texto libre en OCs y Gastos.
-- Los typos generaban duplicados y dificultaban reportes consistentes.

CREATE TABLE IF NOT EXISTS CentrosCosto (
  id_centro_costo INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre        VARCHAR(120) NOT NULL UNIQUE,
  tipo          TEXT CHECK (tipo IN ('OFICINA','PROYECTO','ALMACEN','OTRO')) NOT NULL DEFAULT 'OTRO',
  descripcion   VARCHAR(300),
  activo        BOOLEAN NOT NULL DEFAULT TRUE,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS centroscosto_tipo ON CentrosCosto (tipo);
CREATE INDEX IF NOT EXISTS centroscosto_activo ON CentrosCosto (activo);
