-- 035_alertas_historial.sql
-- Tabla para tracking histórico del ciclo de vida de cada alerta.
-- Cada vez que el endpoint /api/alertas se ejecuta, AlertasService:
--   1. Calcula alertas activas hoy
--   2. INSERT a esta tabla las que aparecen por primera vez
--   3. UPDATE fecha_resuelta=NOW() para las que ya no están activas
-- Así el usuario puede ver el historial en la página de Alertas.

CREATE TABLE IF NOT EXISTS AlertasHistorial (
  id_log INTEGER GENERATED BY DEFAULT AS IDENTITY,
  alerta_id VARCHAR(80) NOT NULL,           -- el id determinístico de AlertasService
  modulo VARCHAR(30) NOT NULL,              -- ALMACEN, COMERCIAL, FINANZAS, LOGISTICA
  tipo VARCHAR(40) NOT NULL,                -- STOCK, COBRANZA_VENCIDA, etc
  severidad VARCHAR(10) NOT NULL,           -- info / warn / danger
  titulo VARCHAR(200) NOT NULL,
  detalle VARCHAR(300),
  link VARCHAR(100),
  fecha_aparicion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  fecha_resuelta TIMESTAMPTZ DEFAULT NULL,  -- NULL = aún activa
  PRIMARY KEY (id_log)
);

-- Índices para queries comunes
CREATE INDEX IF NOT EXISTS idx_alh_activa ON AlertasHistorial (fecha_resuelta)
  WHERE fecha_resuelta IS NULL;
CREATE INDEX IF NOT EXISTS idx_alh_alerta_id ON AlertasHistorial (alerta_id, fecha_resuelta);
CREATE INDEX IF NOT EXISTS idx_alh_modulo ON AlertasHistorial (modulo);
CREATE INDEX IF NOT EXISTS idx_alh_aparicion ON AlertasHistorial (fecha_aparicion DESC);
